# Generated by Django 2.1.5 on 2020-06-19 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='documents/')),
                ('skill', models.CharField(max_length=25, null=True)),
                ('experience', models.CharField(choices=[('選択してください', '選択してください'), ('半年未満', '半年未満'), ('～１年', '～１年'), ('～２年', '～２年'), ('～３年', '～３年'), ('３年～', '３年～')], max_length=25, null=True)),
                ('self_introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_title', models.CharField(max_length=100)),
                ('recruit_content', models.TextField()),
                ('category', models.CharField(choices=[('勉強会', '勉強会'), ('サービス開発', 'サービス開発'), ('その他', 'その他')], max_length=25, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('recruit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
