# Generated by Django 2.1.5 on 2020-06-20 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20200620_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
