# Generated by Django 2.1.5 on 2020-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20200701_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='target',
        ),
        migrations.AddField(
            model_name='profile',
            name='experience1',
            field=models.CharField(choices=[('選択してください', '選択してください'), ('半年未満', '半年未満'), ('～１年', '～１年'), ('～２年', '～２年'), ('～３年', '～３年'), ('３年～', '３年～')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience2',
            field=models.CharField(choices=[('選択してください', '選択してください'), ('半年未満', '半年未満'), ('～１年', '～１年'), ('～２年', '～２年'), ('～３年', '～３年'), ('３年～', '３年～')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience3',
            field=models.CharField(choices=[('選択してください', '選択してください'), ('半年未満', '半年未満'), ('～１年', '～１年'), ('～２年', '～２年'), ('～３年', '～３年'), ('３年～', '３年～')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience4',
            field=models.CharField(choices=[('選択してください', '選択してください'), ('半年未満', '半年未満'), ('～１年', '～１年'), ('～２年', '～２年'), ('～３年', '～３年'), ('３年～', '３年～')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience5',
            field=models.CharField(choices=[('選択してください', '選択してください'), ('半年未満', '半年未満'), ('～１年', '～１年'), ('～２年', '～２年'), ('～３年', '～３年'), ('３年～', '３年～')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill5',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
