# Generated by Django 2.1.5 on 2020-07-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20200702_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=25, null=True)),
                ('experience', models.CharField(choices=[('選択してください', '選択してください'), ('半年未満', '半年未満'), ('～１年', '～１年'), ('～２年', '～２年'), ('～３年', '～３年'), ('３年～', '３年～')], max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill5',
        ),
        migrations.AddField(
            model_name='skill',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Profile'),
        ),
    ]
