# Generated by Django 2.1.5 on 2020-07-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20200706_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='rec_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Recruit'),
        ),
    ]
